### ISSUE TITLE
ConvertFormsToNative only renders the outer view for Map Callout.

### ISSUE THREAD

**Issue by ChaseFlorell** [rid00z/LoadingFormsViewFromNative#1]
On iOS, I'm using 

```
    private static MKAnnotationView GetViewForAnnotation(MKMapView mapView, IMKAnnotation annotation)
    {
       // create annotationView (MKAnnotationView)

        var mc = new _MapCallout();
        var view = FormsViewToNative.ConvertFormsToNative(mc, new CGRect(0, 0, mc.WidthRequest, mc.HeightRequest));

        annotationView.DetailCalloutAccessoryView = view;

        return annotationView;
    }
```

On Android I'm using

```
public class OutageMapCalloutAdapter : Object, GoogleMap.IInfoWindowAdapter
{
    public View GetInfoContents(Marker marker)
    {
        var mc = new _MapCallout();
        return FormsToNative.ConvertFormsToNative(mc, new Rectangle(0, 0, mc.WidthRequest, mc.HeightRequest));
    }

    public View GetInfoWindow(Marker marker)
    {
        return null;
    }
}
```

And for a View, I'm using.

```
<?xml version="1.0" encoding="utf-8"?>

<ContentView xmlns="http://xamarin.com/schemas/2014/forms"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           x:Class="Fortis.OutageMap.UI.Pages.Controls._MapCallout" BackgroundColor="Red" WidthRequest="20" HeightRequest="20">
  <StackLayout HorizontalOptions="Start" VerticalOptions="Start">
      <Label Text="Outage Report" VerticalOptions="Start" HorizontalOptions="Center" TextColor="Black" />
      <Label Text="Foo bar baz" TextColor="Black" />
  </StackLayout>
</ContentView>
```

And when I run up my app, I only see a red box on each platform (not the inner content).

Have you seen this before?

![img_0012](https://cloud.githubusercontent.com/assets/471626/10521658/55ee2a5e-732e-11e5-9e1d-d774109b98ff.PNG)  
![screenshot_2015-10-15-11-11-08](https://cloud.githubusercontent.com/assets/471626/10521659/55f890de-732e-11e5-8486-d505438d4ddb.png)

**Comment by rid00z** [comment]
Maybe use a StackLayout directly rather than have the content view?

On Friday, 16 October 2015, Chase Florell notifications@github.com wrote:

> On iOS, I'm using
> 
> ```
> private static MKAnnotationView GetViewForAnnotation(MKMapView mapView, IMKAnnotation annotation)
> {
>    // create annotationView (MKAnnotationView)
> 
>     var mc = new _MapCallout();
>     var view = FormsViewToNative.ConvertFormsToNative(mc, new CGRect(0, 0, mc.WidthRequest, mc.HeightRequest));
> 
>     annotationView.DetailCalloutAccessoryView = view;
> 
>     return annotationView;
> }
> ```
> 
> On Android I'm using
> 
> public class OutageMapCalloutAdapter : Object, GoogleMap.IInfoWindowAdapter
> {
>     public View GetInfoContents(Marker marker)
>     {
>         var mc = new _MapCallout();
>         return FormsToNative.ConvertFormsToNative(mc, new Rectangle(0, 0, mc.WidthRequest, mc.HeightRequest));
>     }
> 
> ```
> public View GetInfoWindow(Marker marker)
> {
>     return null;
> }
> ```
> 
> }
> 
> And for a View, I'm using.
> 
> <?xml version="1.0" encoding="utf-8"?>
> 
> <ContentView xmlns="http://xamarin.com/schemas/2014/forms"
>            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>            x:Class="Fortis.OutageMap.UI.Pages.Controls._MapCallout" BackgroundColor="Red" WidthRequest="20" HeightRequest="20">
>   <StackLayout HorizontalOptions="Start" VerticalOptions="Start">
>       <Label Text="Outage Report" VerticalOptions="Start" HorizontalOptions="Center" TextColor="Black" />
>       <Label Text="Foo bar baz" TextColor="Black" />
>   </StackLayout>
> </ContentView>
> 
> And when I run up my app, I only see a red box on each platform (not the
> inner content).
> 
> Have you seen this before?
> 
> [image: img_0012]
> https://cloud.githubusercontent.com/assets/471626/10521658/55ee2a5e-732e-11e5-9e1d-d774109b98ff.PNG
> 
> [image: screenshot_2015-10-15-11-11-08]
> https://cloud.githubusercontent.com/assets/471626/10521659/55f890de-732e-11e5-8486-d505438d4ddb.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rid00z/LoadingFormsViewFromNative/issues/1.

## 

_Michael Ridland | Technical Director | Xamarin MVP_

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by ChaseFlorell** [comment]
Yeah, I tried that also, still only rendered the StackLayout and the inner labels didn't "inflate"
